### ISSUE TITLE
Extension Displays "en;q" et Cetera

### ISSUE THREAD

**Issue by patrickdark** [callahad/quick-accept-language-switcher#5] opened 2017-04-22 02:22 UTC
If the header string is something like "en;q=1", then "en;q" is displayed over the icon. Not sure if this is intentional or not. (Edit: Seems unintentional since "eng;q=0" displays "eng;".)

If the header string is contains invalid values like "en;q", "en;x", or "en=x", then "en;q", "en;x", and "en=" are displayed respectively. Seem like bugs.

**Comment by callahad** [comment] 2017-04-26 14:05
Let's call this a dupe of #7

**Closed as completed by callahad** 2017-04-26 14:05 UTC
